### PR TITLE
Fix Redshift convert timezone macro

### PR DESCRIPTION
**Pull request by wellykachtel**
when trying to compile any model, I was getting the error `default__convert_timezone is undefined`. This fixes the issue by specifying the package where the macro `default__convert_timezone` is defined, even though it's in the same file. This bug was introduced [here](https://github.com/calogica/dbt-date/pull/63).

### CODE REVIEW

**Comment by clausherther** [comment]
ugh, we really bungled this one, thanks for raising this @wellykachtel! Will take a look as soon as I can.

**Comment by clausherther** [comment]
Code looks good to me, but I don't have a way to test this on Redshift and therefore don't really support RS. @wellykachtel were you able to run this on Redshift?

**Comment by clausherther** [comment]
hey @wellykachtel ! I was having a hard time rebasing your branch to get the CI for PRs to work, so I opened a new PR #71 with the fix which I'll merge and release today. Thanks again for flagging this bug!

**Comment by wellykachtel** [comment]
@clausherther thank you for resolving this!

**Pull request closed without merging**
