### PR TITLE
Add Trino support

### LINKED ISSUE #114: Trino support
I would be awesome if we could add Trino support to dbt-date.

Currently, we maintain a separate package called `dbt-trino-utils` containing Trino-specific macro implementations.
However, as this package continues to grow with new additions, it introduces certain challenges.
Some of these packages have different dbt-core version requirements, which force us to use a lower version
for one of the packages.

It would be more efficient to directly add Trino implementations for a few macros into dbt-date
rather than replicating the entire test suite on our side.

Furthermore, this approach offers a more user-friendly experience as users won't need to install an additional package and make extra configurations in their dbt_project.yml file.

Regarding testing, we can set up a Docker container with a Trino image in CI and run tests on it.

### PR DESCRIPTION
**Pull request by damian3031**
resolves #114 

I'm not sure if I've set up CircleCI properly, as I'm not familiar with it. Your assistance would be greatly appreciated 🙂

### CODE REVIEW

**Comment by clausherther** [comment]
Thanks! Let me look over this over the weekend and think about whether we want to get into supporting Trino in our repo.

**Comment by clausherther** [comment]
FYI, CI is failing on the docker container https://app.circleci.com/pipelines/github/calogica/dbt-date/138/workflows/ae42adc3-3f8f-4733-8bfa-a3e181cc2901/jobs/151/parallel-runs/0/steps/0-106

In my experience, debugging CircleCI or any CI is a major pain which is why that's been the biggest blocker for adding new platform support.

**Comment by clausherther** [comment]
@damian3031 CI still erroring out
https://app.circleci.com/pipelines/github/calogica/dbt-date/139/workflows/d624876c-ff97-43c3-92e2-70b5724d13a8/jobs/157/parallel-runs/0/steps/0-107

**Comment by damian3031** [comment]
@clausherther I've set up CircleCI in my fork and made sure that the CI is passing. There shouldn't be any errors now.

**Review by clausherther — APPROVED** [review]
Looks good, thanks!

**Comment by clausherther** [comment]
Looks good. I think you need a rebase to resolve those conflicts and then we're good to go!

**Comment by clausherther** [comment]
> Looks good. I think you need a rebase to resolve those conflicts and then we're good to go!

nm, looks like you did already ;)

**Comment by damian3031** [comment]
Awesome! Thanks for releasing it quickly!

**Pull request merged**
