### PR TITLE
feat: add round timestamp macro

### PR DESCRIPTION
**Pull request by jpmmcneill**
Small macro which I find helpful.

It's quite similar to the typical sql `date_trunc` in that it returns a date, but it returns the _closest_ date to a given timestamp.

### CODE REVIEW

**Comment by clausherther** [comment]
Hi @jpmmcneill, thanks for this! (And sorry for only getting to this now.)
This looks very useful indeed. I'll take a look and let you know if I have any questions.

**Comment by clausherther** [comment]
@jpmmcneill looks like we have a test failure here: https://app.circleci.com/pipelines/github/calogica/dbt-date/21/workflows/19108182-7ac3-440f-8e7c-27be40fc8df6/jobs/16?invite=true#step-104-70
I don't think we need the double quotes around the datepart maybe?

**Comment by clausherther** [comment]
FYI, getting similar errors on BigQuery, but not SF (I assume that's where you tested this?).

**Comment by clausherther** [comment]
Oe more thing: even if I remove the quotes, the test fails on BigQuery b/c the integration test is comparing a `date` to the result of the `date_trunc` op which is a `timestamp`.
`No matching signature for operator = for argument types: DATE, TIMESTAMP`

```sql
where not(rounded_timestamp = 
    timestamp_trunc(
        cast(

        datetime_add(
            cast( time_stamp as datetime),
        interval 12 hour
        )

 as timestamp),
        day
    )
)
```
Since the macro is called round_timestamp, I think it's correct to return a timestamp and not a date, so maybe we want to adjust the integration test?

**Comment by clausherther** [comment]
@jpmmcneill fyi, pushed a couple of commits that I think address my comments above.

**Review by clausherther — APPROVED** [review]
LGTM

**Comment by jpmmcneill** [comment]
Thanks @clausherther! Appreciate the commits. I think that this is good to be merged now

**Comment by clausherther** [comment]
I'll do releases for dbt-date and dbt-expectations this weekend.

**Pull request merged**
